<?php

/**
 * @file
 * Hooks and functionality for the Commerce Cart Advanced module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Hooks.
 */

/**
 * Implements hook_theme().
 */
function commerce_cart_advanced_theme($existing, $type, $theme, $path) {
  return [
    'commerce_cart_advanced_current' => [
      'variables' => [
        'carts' => NULL,
      ],
    ],
    'commerce_cart_advanced_non_current' => [
      'variables' => [
        'carts' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_form_FORM_ID_alter() for 'commerce_order_type_form'.
 */
function commerce_cart_advanced_form_commerce_order_type_form_alter(array &$form, FormStateInterface $form_state) {
  /** @var \Drupal\commerce_order\Entity\OrderTypeInterface $order_type */
  $order_type = $form_state->getFormObject()->getEntity();
  $view_storage = \Drupal::entityTypeManager()->getStorage('view');
  $available_form_views = [];
  foreach ($view_storage->loadMultiple() as $view) {
    if (strpos($view->get('tag'), 'commerce_cart_form') !== FALSE) {
      $available_form_views[$view->id()] = $view->label();
    }
  }

  $form['commerce_cart']['cart_form_non_current_view'] = [
    '#type' => 'select',
    '#title' => t('Non-current shopping carts form view'),
    '#options' => $available_form_views,
    '#default_value' => $order_type->getThirdPartySetting(
      'commerce_cart_advanced',
      'cart_form_view',
      'commerce_cart_form_non_current'
    ),
  ];

  $form['commerce_cart']['cart_form_view']['#title'] = t('Current shopping carts form view');

  $form['actions']['submit']['#submit'][] = '_commerce_cart_advanced_order_type_form_submit';
}

/**
 * Callbacks.
 */

/**
 * Submit handler for order type edit form.
 */
function _commerce_cart_advanced_order_type_form_submit($form, FormStateInterface $form_state) {
  /** @var \Drupal\commerce_order\Entity\OrderTypeInterface $order_type */
  $order_type = $form_state->getFormObject()->getEntity();
  $settings = $form_state->getValue(['commerce_cart']);
  $order_type->setThirdPartySetting(
    'commerce_cart_advanced',
    'cart_form_view',
    $settings['cart_form_non_current_view']
  );
  $order_type->save();
}
